import type { NextPage } from 'next'
import Head from 'next/head'
import { Flex, Spacer } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <Flex h="100%">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      test
    </Flex>
  )
}

export default Home
